export const CREATE_PROJECT = "CREATE_PROJECT"
export const RETRIVE_PROJECTS = "RETRIVE_PROJECTS"
export const DELETE_PROJECT = "DELETE_PROJECT"

export const CREATE_CONTACT = "CREATE_CONTACT"
export const RETRIVE_CONTACTS = "RETRIVE_CONTACTS"
export const DELETE_CONTACT = "DELETE_CONTACT"